language: python
python:
    - '3.8'
    - '3.7'
    - '3.6'
    - '2.7'
env:
  - CYTHON="<=0.29.21"
  - CYTHON=">0.29.21"
install:
  - pip install -U Cython${CYTHON}
  - travis_retry python setup.py develop
script: "py.test tests/"
