name: build autowrap

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel
      # depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 8
      fail-fast: false
      matrix:
        include:
          - CYTHON: "<=0.29.21"
            python-version: "2.7"
          - CYTHON: "<=0.29.21"          
            python-version: "3.6"
          - CYTHON: "<=0.29.21"
            python-version: "3.7"
          - CYTHON: "<=0.29.21"          
            python-version: "3.8"
          - CYTHON: "<=0.29.21"          
            python-version: "3.9"
          - CYTHON: ">0.29.21"
            python-version: "2.7"
          - CYTHON: ">0.29.21"          
            python-version: "3.6"
          - CYTHON: ">0.29.21"
            python-version: "3.7"
          - CYTHON: ">0.29.21"          
            python-version: "3.8"
          - CYTHON: ">0.29.21"          
            python-version: "3.9"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip
      - name: Install pytest
        run: |
          python -m pip install pytest
      - name: Upgrade cython version
        run: |
          python -m pip install "Cython${{ matrix.CYTHON }}"
      - name: run tests
        run: |
          python setup.py develop
          py.test tests/
